import Head from "next/head"
import { Col, Row } from "antd"
import Compare from "./compare"
import AesCard from "./aesCard"
import SHA256Card from "./sha256Card"

export default function Home() {
  return (
    <>
      <Head>
        <title>zkPass vole-in-the-head Demo</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Row gutter={[16, 16]}>
        <Col span={12} offset={6}>
          <Compare />
        </Col>
        <Col span={12} offset={6}>
          <AesCard />
        </Col>
        <Col span={12} offset={6}>
          <SHA256Card />
        </Col>
      </Row>
    </>
  )
}
