// Web Proof: the synthetic HTTPS session the prover library's fixture proves, loaded from
// `public/fixtures/session.json` (generated by the library's `real_circuit/session.rs`). The
// statement is read from the fixture bytes; the lies change one constant node of it.
import { constantCircuit } from "../zk-build/circuit"
import { Statement } from "../zk-build/types"
import { NodeOutput, statementFromBytes } from "../zk-build"
import { bytesFromWires, fromHex, hex, utf8 } from "../utils"
import { CircuitNode, circuitNodes, Claim, Row } from "./types"

export interface Session {
  waterfall: string
  inputs: string
  request: string
  response: string
  statementAddress: string
  publicField: string
  cipherBlocks: string[]
  proofBytes: { 4: number; 8: number }
  nodes: { id: number; name: string; out: boolean }[]
}

export interface Params {
  session: Session
  /** The address the prover claims the request carries, when it lies about the statement. */
  claimedAddress?: string
}

/** The constant nodes the lies rewrite: the address the request must carry, and the first cipher
 *  block (`request_cipher_0_i` holds text block 4 − i). */
const ADDRESS_NODE = "request_value_0_1_0"
const CIPHER_NODE = "request_cipher_0_4"
const CIPHER_BLOCK = 0
const CHANGED_BYTE = 5

const LIE_ADDRESS = "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"

export function build({ session, claimedAddress }: Params): Claim {
  const statement = statementFromBytes(fromHex(session.waterfall))
  if (claimedAddress !== undefined) statement.circuits[ADDRESS_NODE] = constantCircuit(utf8(claimedAddress))
  return { statement, witness: [...session.inputs].map((bit) => bit === "1") }
}

export const falseClaim = (p: Params): Params => ({ ...p, claimedAddress: LIE_ADDRESS })

/** Other cipher records: the proven statement with one byte of the first cipher block changed. */
export function otherStatement(p: Params): Statement {
  const { statement } = build(p)
  statement.circuits[CIPHER_NODE] = constantCircuit(otherBlock(p.session))
  return statement
}

function otherBlock(session: Session): Uint8Array {
  const block = fromHex(session.cipherBlocks[CIPHER_BLOCK])
  block[CHANGED_BYTE] ^= 1
  return block
}

const holds = ({ session, claimedAddress }: Params): boolean => claimedAddress === undefined || claimedAddress === session.statementAddress

export function rows(p: Params, outputs?: NodeOutput[]): Row[] {
  const { session } = p
  const checks = outputs ? outputs[0].groups[0][0] : holds(p)
  const level = outputs ? new TextDecoder().decode(bytesFromWires(outputs[1].groups[0])) : session.publicField
  const address = p.claimedAddress ?? session.statementAddress
  const blocks = `· ${session.cipherBlocks.length} blocks`
  return [
    { label: "request", kind: "prover", text: session.request },
    { label: "response", kind: "prover", text: session.response },
    {
      label: "ciphertext",
      kind: "verifier",
      text: `${session.cipherBlocks[CIPHER_BLOCK]} ${blocks}`,
      caption: "in production, signed by the TLS proxy; here a fixture",
      action: {
        kind: "otherStatement",
        label: "check against another session",
        alt: { text: `${hex(otherBlock(session))} ${blocks}`, note: "other cipher records: one byte of the first block changed" },
      },
    },
    {
      label: "statement",
      kind: "public",
      text: `address = ${address.slice(0, 10)}…, reveal "level"`,
      action: { kind: "falseClaim", label: "claim another address" },
    },
    {
      label: "all checks",
      kind: "claim",
      ok: checks,
      text: `${checks} · ${checks ? "every check passed" : "the address in the request is not the one in the statement"}`,
    },
    { label: "level", kind: "result", text: `"${level}"` },
  ]
}

export const circuit = ({ session }: Params): CircuitNode[] => circuitNodes(statementFromBytes(fromHex(session.waterfall)))
